name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code

    - name: print cow      # Name of step
      run: echo cow           # Command to run
    
    - name: Test Javascript Hello Action
      uses: adeloyedeji/github-actions-hello@v1.0 # from marketplace
      
      with:
        who-to-greet: "Come on Liverpool for Champions League"

    - name: build c# code
      run: dotnet build
      
    - name: test c# code
      run: dotnet test

    - name: npm install
      run: npm install
      working-directory: DotnetTemplate.Web
    
    - name: npm run build
      run: npm run build
      working-directory: DotnetTemplate.Web

    - name: npm t
      run: npm t
      working-directory: DotnetTemplate.Web

    - name: npm run lint
      run: npm run lint
      working-directory: DotnetTemplate.Web
    
    - name: dotnet run
      run: dotnet run
      working-directory: DotnetTemplate.Web
